name: Achintya Prakash
description: Blog - Achintya Prakash
url: achintp.github.io/meraki


#Author info
author_name: Achintya Prakash

#contacts
author_github: https://github.com/achintp
author_linkedin: http://www.linkedin.com/in/achintyaprakash
author_twitter: https://twitter.com/achintp
author_about: http://www.sanger.dk/



#rendering settings
markdown: redcarpet
pygments: true

permalink: /meraki/:year/:month/:day/:title/
