name: Achintya Prakash
description: Blog - Achintya Prakash
baseurl: "http://achintp.github.io/meraki"


#Author info
author_name: Achintya Prakash

#contacts
author_github: https://github.com/achintp
author_linkedin: http://www.linkedin.com/in/achintyaprakash
author_twitter: https://twitter.com/achintp
author_about: http://www.sanger.dk/



#rendering settings
markdown: kramdown
pygments: true

relative_permalinks: false
permalink: :year/:month/:day/:title.html


